### ISSUE TITLE
[Bug]: TCG2/TPM2 support on aarch64 does not work

### ISSUE THREAD

**Issue by r1chard-lyu** [tianocore/edk2#11509]
### Is there an existing issue for this?

- [x] I have searched existing issues

### Bug Type

- [x] Firmware
- [ ] Tool
- [ ] Unit Test

### What packages are impacted?

OvmfPkg

### Which targets are impacted by this bug?

DEBUG

### Current Behavior

When booting OVMF in QEMU, it gets stuck at “Loading Tcg2Pei.efi.
```
Loading PEIM at 0x0000003E160 EntryPoint=0x000000403C8 Tcg2ConfigPei.efi
Tcg2ConfigPeimEntryPoint
Tcg2ConfigPeimEntryPoint: TPM2 detected
Install PPI: 7F4158D3-074D-456D-8CB2-01F9C8F79DAA
Loading PEIM A0C98B77-CBA5-4BB8-993B-4AF6CE33ECE4
add-symbol-file /home/r1chard/Workspace/edk2/Build/ArmVirtQemu-AARCH64/DEBUG_GCC5/AARCH64/SecurityPkg/Tcg/Tcg2Pei/Tcg2Pei/DEBUG/Tcg2Pei.dll 0x42240
Loading PEIM at 0x00000042160 EntryPoint=0x0000004C174 Tcg2Pei.efi
Synchronous Exception at 0x446FC
```

### Expected Behavior

Loading Tcg2Pei.efi succeeds and does not hang.

### Steps To Reproduce

Build OVMF using
```
build -D TPM2_ENABLE -D TPM2_CONFIG_ENABLE -D NETWORK_IP6_ENABLE -D NETWORK_HTTP_BOOT_ENABLE -D SECURE_BOOT_ENABLE -D NETWORK_TLS_ENABLE -a AARCH64 -p ArmVirtPkg/ArmVirtQemu.dsc -b DEBUG -t GCC5
truncate -s 64M Build/ArmVirtQemu-AARCH64/DEBUG_GCC5/FV/QEMU_EFI.fd
````
Start swtpm using
```
mkdir /tmp/tpm0
swtpm socket --tpmstate dir=/tmp/tpm0 --ctrl type=unixio,path=/tmp/tpm0/swtpm-sock --tpm2 --log level=20
```
and start emulation using
```
qemu-system-aarch64   -M virt   -cpu cortex-a57   -m 1024   -serial stdio   -drive file=Build/ArmVirtQemu-AARCH64/DEBUG_GCC5/FV/QEMU_EFI.fd,if=pflash,format=raw,readonly=on   -chardev socket,id=chrtpm,path=/tmp/tpm0/swtpm-sock   -tpmdev emulator,id=tpm0,chardev=chrtpm   -device tpm-tis-device,tpmdev=tpm0
```

### Build Environment

```markdown
- OS(s): openSUSE Tumbleweed
- Tool Chain(s): GCC5
```

### Version Information

```text
Tag: edk2-stable202508
```

### Urgency

Medium

### Are you going to fix this?

Someone else needs to fix it

### Do you need maintainer feedback?

Maintainer feedback requested

**Comment by lgao4** [comment]
@r1chard-lyu , could you provide the full call stack in the boot log?

**Comment by r1chard-lyu** [comment]
How can I generate the full call stack in the boot log? 
I set PcdDebugPrintErrorLevel to 0xFFFFFFFF in ArmVirtPkg/ArmVirtQemu.dsc. Is it this attachment?

[ovmf-aarch64.log](https://github.com/user-attachments/files/22397462/ovmf-aarch64.log)

**Comment by r1chard-lyu** [comment]
After bisec, commit 460f2705b4 SecurityPkg: Add Additional TPM Logging at DEBUG_SECURITY caused this issue.

5a2713ec2b MdeModulePkg/Library: commonize some duplicate code in ArmFfaLib
a7e27682cf MdeModulePkg/Library: add ArmFfaSecLib
bbd810221e MdeModulePkg: Make PcdFfaTxRxPageCount a PcdsFixedAtBuild PCD
b336d9b87a MdeModulePkg/Library: fix memory leak Rx/Tx Buffer in ArmFfaPeiLib
460f2705b4 SecurityPkg: Add Additional TPM Logging at DEBUG_SECURITY         <--- X
d5b8630379 SecurityPkg: Move Noisy Logs to DEBUG_SECURITY
1f2adcbba5 SecurityPkg: Remove/Downgrade Noisy TCG Prints
dbf45a870b MdePkg: Add DEBUG_SECURITY Bit in PcdDebugPrintErrorLevel

**Comment by lgao4** [comment]
@os-d , could you help check this issue?

**Comment by os-d** [comment]
@lgao4 , I believe this issue was resolved with this commit: https://github.com/tianocore/edk2/commit/21eff866e7a8e7e9669ec3448a4a3f455a67f2f8.

@r1chard-lyu can you please confirm if top of tree edk2 has the issue?

**Comment by r1chard-lyu** [comment]
Yes, I tried the commit 21eff86, it works well, but the top of tree edk2 has another issue. The log is shown in the attachment.

[ovmf-debug.log](https://github.com/user-attachments/files/23204803/openSUSE-Tumbleweed-aarch64-20250826-ovmf-debug.log)

**Comment by r1chard-lyu** [comment]
But with this new issue, even after I disabled the TPM, the issue still exists, so it’s probably not related to TPM. Maybe I should open another bug?
