### ISSUE TITLE
[Bug]: RedfishPkg fails to build with 'lld-link: error: undefined symbol: _memcpy' in CLANGPDB (IA32 NOOPT)

### ISSUE THREAD

**Issue by mikebeaton** [tianocore/edk2#11882]
### Is there an existing issue for this?

- [x] I have searched existing issues

### Bug Type

- [x] Firmware
- [ ] Tool
- [ ] Unit Test

### What packages are impacted?

RedfishPkg

### Which targets are impacted by this bug?

NOOPT

### Current Behavior

 `build -p RedfishPkg/RedfishPkg.dsc -a IA32 -b NOOPT -t CLANGPDB` fails with:

```
lld-link: error: undefined symbol: _memcpy
>>> referenced by /home/vsts/w/edk2/RedfishPkg/RedfishPlatformConfigDxe/RedfishPlatformConfigDxe.c:1971
```

### Expected Behavior

The package should build in this configuration.

### Steps To Reproduce

`build -p RedfishPkg/RedfishPkg.dsc -a IA32 -b NOOPT -t CLANGPDB` fails with the `_memcpy` error given above.

`build -p RedfishPkg/RedfishPkg.dsc -a X64 -b NOOPT -t CLANGPDB` does not fail.

### Build Environment

```markdown
- OS(s): fedora (CI build image)
- Tool Chain(s): CLANGPDB
```

### Version Information

```text
I have not checked for earliest commit. edk2/master.
```

### Urgency

Medium

### Are you going to fix this?

I will fix it

### Do you need maintainer feedback?

Maintainer feedback requested

### Anything else?

https://github.com/tianocore/edk2/issues/11881 is a closely related issue, but there is a [reasonable fix](https://github.com/tianocore/edk2/pull/11877) for that which does not fix this.

**Comment by lgao4** [comment]
@mikebeaton , can this one be closed? seemly, it has been fixed.

**Comment by mikebeaton** [comment]
CI will not check IA32 NOOPT, so I am not sure whether it is fixed, will check when I get a chance.

**Comment by mikebeaton** [comment]
Hi @lgao4 - Apologies for the delay, I checked and unfortunately the error is still present, specific to IA32 NOOPT.

**Comment by lgao4** [comment]
For this problem, the fix is to find the source code that trigs memcpy, then use BaseMemoryLib CopyMem for it. Can you disassmbly the generated RedfishPlatformConfigDxe.obj and find the specific code that uses memcpy?

**Comment by mdkinney** [comment]
I have reproduced this issue.

Unfortunately, the root cause is a design issue in the RedFishPkg libraries and protocols.  They have defined APIs that pass a structure by value instead of passing a structure by reference and the compiler has to copy the structure contents of the parameter when making a call. Depending on the compiler optimizations, this can result in the use of the intrinsic memcpy().  The parameter `Value` of type `EDKII_REDFISH_VALUE`  should be `*Value` to follow the EDK II C Coding Standards Specification.  Section 5.7.4.1 (https://tianocore-docs.github.io/edk2-CCodingStandardsSpecification/draft/5_source_files/57_c_programming.html#57-c-programming) states "Never pass structures as function parameters by value. Use the "address of" operator, '&', and pass structures by reference."


```
EFI_STATUS
EFIAPI
RedfishPlatformConfigProtocolSetValue (
  IN     EDKII_REDFISH_PLATFORM_CONFIG_PROTOCOL  *This,
  IN     CHAR8                                   *Schema,
  IN     CHAR8                                   *Version,
  IN     EFI_STRING                              ConfigureLang,
  IN     EDKII_REDFISH_VALUE                     Value
  )
```

```
EFI_STATUS
RedfishPlatformConfigSetValue (
  IN     CHAR8                *Schema,
  IN     CHAR8                *Version,
  IN     EFI_STRING           ConfigureLang,
  IN     EDKII_REDFISH_VALUE  Value
  );
```

@AbnerChang  Please review this issue and update the RedfishPkg to not have any APIs that pass structures by value.

**Comment by changab** [comment]
> I have reproduced this issue.
> 
> Unfortunately, the root cause is a design issue in the RedFishPkg libraries and protocols. They have defined APIs that pass a structure by value instead of passing a structure by reference and the compiler has to copy the structure contents of the parameter when making a call. Depending on the compiler optimizations, this can result in the use of the intrinsic memcpy(). The parameter `Value` of type `EDKII_REDFISH_VALUE` should be `*Value` to follow the EDK II C Coding Standards Specification. Section 5.7.4.1 (https://tianocore-docs.github.io/edk2-CCodingStandardsSpecification/draft/5_source_files/57_c_programming.html#57-c-programming) states "Never pass structures as function parameters by value. Use the "address of" operator, '&', and pass structures by reference."
> 
> ```
> EFI_STATUS
> EFIAPI
> RedfishPlatformConfigProtocolSetValue (
>   IN     EDKII_REDFISH_PLATFORM_CONFIG_PROTOCOL  *This,
>   IN     CHAR8                                   *Schema,
>   IN     CHAR8                                   *Version,
>   IN     EFI_STRING                              ConfigureLang,
>   IN     EDKII_REDFISH_VALUE                     Value
>   )
> ```
> 
> ```
> EFI_STATUS
> RedfishPlatformConfigSetValue (
>   IN     CHAR8                *Schema,
>   IN     CHAR8                *Version,
>   IN     EFI_STRING           ConfigureLang,
>   IN     EDKII_REDFISH_VALUE  Value
>   );
> ```
> 
> [@AbnerChang](https://github.com/AbnerChang) Please review this issue and update the RedfishPkg to not have any APIs that pass structures by value.

@mdkinney , I am looking at this. Thanks.

**Comment by changab** [comment]
@mdkinney  Please check https://github.com/tianocore/edk2/pull/12006

**Comment by mikebeaton** [comment]
> [@mdkinney](https://github.com/mdkinney) Please check [#12006](https://github.com/tianocore/edk2/pull/12006)

Could you add `Fixes: #11882` to the commit message there? Will link to this and GitHub will auto-close this when merged. Many thanks!

**Comment by mikebeaton** [comment]
Hi This wasn't auto-closed, as the [commit message](https://github.com/tianocore/edk2/commit/60bfa52f6520bff0aa265c3e89ef9d6f6aeca5e7) didn't have the specific `Fixes: ...` format, but it is now fixed.
